### ISSUE TITLE
# 2. Training - ImportError: cannot import name '_linear'

### ISSUE THREAD

**Issue by alphaaurigae** [allenai/bi-att-flow#49]
OS 16.04
Python 3 , python 2 also has an err
branch master

✘-1 ~/github/bi-att-flow/allenai/bi-att-flow [master|…32] 
23:40 $ python3 -m basic.cli --mode train --noload --debug
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tux/github/bi-att-flow/allenai/bi-att-flow/basic/cli.py", line 5, in <module>
    from basic.main import main as m
  File "/home/tux/github/bi-att-flow/allenai/bi-att-flow/basic/main.py", line 14, in <module>
    from basic.model import get_multi_gpu_models
  File "/home/tux/github/bi-att-flow/allenai/bi-att-flow/basic/model.py", line 10, in <module>
    from my.tensorflow.nn import softsel, get_logits, highway_network, multi_conv1d
  File "/home/tux/github/bi-att-flow/allenai/bi-att-flow/my/tensorflow/nn.py", line 1, in <module>
    from tensorflow.python.ops.rnn_cell import _linear
ImportError: cannot import name '_linear'
✘-1 ~/github/bi-att-flow/allenai/bi-att-fl

**Comment by unilight** [comment]
I guess you need an older version of tf?

**Comment by alphaaurigae** [comment]
forgot to close the issue. It appears the master branch is build on 14.04 and dev build on 16.04.
The dev branch did finally start training but i couldnt run it on my netbook as it was crashing when the cpu started. Ill look into the master tomorrow and see if it works on 14.04

**Comment by alphaaurigae** [comment]
see for reference https://github.com/alphaaurigae/bi-att-flow_bash
